package org.oapen.memoproject.dataingestion.harvest.doabooks;

final class TestConstants {
	
	final static String xmlrecord1 = 
  			"<record>"
  			+ "	<header>"
  			+ "		<identifier>oai:directory.doabooks.org:20.500.12854/45918</identifier>"
  			+ "		<datestamp>2024-04-09T23:16:16Z</datestamp>"
  			+ "		<setSpec>com_20.500.12854_5</setSpec>"
  			+ "		<setSpec>col_20.500.12854_6</setSpec>"
  			+ "	</header>"
  			+ "	<metadata>"
  			+ "		<metadata xmlns=\"http://www.lyncode.com/xoai\""
  			+ "			xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\""
  			+ "			xsi:schemaLocation=\"http://www.lyncode.com/xoai http://www.lyncode.com/xsd/xoai.xsd\">"
  			+ "			<element name=\"dc\">"
  			+ "				<element name=\"contributor\">"
  			+ "					<element name=\"author\">"
  			+ "						<element name=\"*\">"
  			+ "							<field name=\"value\">Riedel, Boris</field>"
  			+ "							<field name=\"authority\">"
  			+ "								5c2d2215-89d0-4e69-9400-fa99ccc8ef00</field>"
  			+ "							<field name=\"confidence\">300</field>"
  			+ "						</element>"
  			+ "					</element>"
  			+ "				</element>"
  			+ "				<element name=\"date\">"
  			+ "					<element name=\"accessioned\">"
  			+ "						<element name=\"none\">"
  			+ "							<field name=\"value\">2021-02-11T12:10:59Z</field>"
  			+ "						</element>"
  			+ "					</element>"
  			+ "					<element name=\"available\">"
  			+ "						<element name=\"none\">"
  			+ "							<field name=\"value\">2021-02-11T12:10:59Z</field>"
  			+ "						</element>"
  			+ "					</element>"
  			+ "					<element name=\"issued\">"
  			+ "						<element name=\"*\">"
  			+ "							<field name=\"value\">2011</field>"
  			+ "						</element>"
  			+ "					</element>"
  			+ "					<element name=\"submitted\">"
  			+ "						<element name=\"*\">"
  			+ "							<field name=\"value\">2019-07-30 20:02:00</field>"
  			+ "						</element>"
  			+ "					</element>"
  			+ "				</element>"
  			+ "				<element name=\"identifier\">"
  			+ "					<element name=\"*\">"
  			+ "						<field name=\"value\">35140</field>"
  			+ "					</element>"
  			+ "					<element name=\"uri\">"
  			+ "						<element name=\"none\">"
  			+ "							<field name=\"value\">"
  			+ "								https://directory.doabooks.org/handle/20.500.12854/45918</field>"
  			+ "						</element>"
  			+ "					</element>"
  			+ "				</element>"
  			+ "				<element name=\"description\">"
  			+ "					<element name=\"abstract\">"
  			+ "						<element name=\"*\">"
  			+ "							<field name=\"value\">Diese Arbeit befasst sich mit"
  			+ "								verschiedenen nano- und mikrotechnologischen"
  			+ "								Konzepten zur Steigerung der Auskoppeleffizienz"
  			+ "								von OLEDs.Hierfür werden drei bottom-up-Ansätze,"
  			+ "								bei denen Nanopartikel während der"
  			+ "								OLED-Herstellung in die OLED eingebracht werden,"
  			+ "								beschrieben und zwei top-down-Ansätze"
  			+ "								vorgestellt, bei denen vor der eigentlichen"
  			+ "								OLED-Herstellung die Substratoberfläche durch"
  			+ "								Nano- und Mikrostrukturierung modifiziert wird.</field>"
  			+ "						</element>"
  			+ "					</element>"
  			+ "				</element>"
  			+ "				<element name=\"language\">"
  			+ "					<element name=\"*\">"
  			+ "						<field name=\"value\">ger</field>"
  			+ "					</element>"
  			+ "				</element>"
  			+ "				<element name=\"subject\">"
  			+ "					<element name=\"*\">"
  			+ "						<field name=\"value\">T1-995</field>"
  			+ "					</element>"
  			+ "					<element name=\"classification\">"
  			+ "						<element name=\"en_US\">"
  			+ "							<field name=\"value\">thema EDItEUR::T Technology,"
  			+ "								Engineering, Agriculture, Industrial"
  			+ "								processes::TB Technology: general issues</field>"
  			+ "						</element>"
  			+ "					</element>"
  			+ "					<element name=\"other\">"
  			+ "						<element name=\"*\">"
  			+ "							<field name=\"value\">Effizienzsteigerung</field>"
  			+ "							<field name=\"value\">Nanostruktur</field>"
  			+ "							<field name=\"value\">Auskopplung</field>"
  			+ "							<field name=\"value\">OLED</field>"
  			+ "							<field name=\"value\">Streuung</field>"
  			+ "						</element>"
  			+ "					</element>"
  			+ "				</element>"
  			+ "				<element name=\"title\">"
  			+ "					<element name=\"*\">"
  			+ "						<field name=\"value\">Effizienzsteigerung in organischen"
  			+ "							Leuchtdioden</field>"
  			+ "					</element>"
  			+ "				</element>"
  			+ "				<element name=\"type\">"
  			+ "					<element name=\"none\">"
  			+ "						<field name=\"value\">book</field>"
  			+ "					</element>"
  			+ "				</element>"
  			+ "			</element>"
  			+ "			<element name=\"oapen\">"
  			+ "				<element name=\"identifier\">"
  			+ "					<element name=\"doi\">"
  			+ "						<element name=\"*\">"
  			+ "							<field name=\"value\">10.5445/KSP/1000023575</field>"
  			+ "						</element>"
  			+ "					</element>"
  			+ "				</element>"
  			+ "				<element name=\"relation\">"
  			+ "					<element name=\"isPublishedBy\">"
  			+ "						<element name=\"*\">"
  			+ "							<field name=\"value\">"
  			+ "								68fffc18-8f7b-44fa-ac7e-0b7d7d979bd2</field>"
  			+ "							<field name=\"authority\">"
  			+ "								68fffc18-8f7b-44fa-ac7e-0b7d7d979bd2</field>"
  			+ "							<field name=\"confidence\">600</field>"
  			+ "						</element>"
  			+ "					</element>"
  			+ "					<element name=\"isbn\">"
  			+ "						<element name=\"*\">"
  			+ "							<field name=\"value\">9783866447004</field>"
  			+ "						</element>"
  			+ "					</element>"
  			+ "				</element>"
  			+ "				<element name=\"pages\">"
  			+ "					<element name=\"*\">"
  			+ "						<field name=\"value\">IX, 193 p.</field>"
  			+ "					</element>"
  			+ "				</element>"
  			+ "			</element>"
  			+ "			<element name=\"peerreview\">"
  			+ "				<element name=\"review\">"
  			+ "					<element name=\"type\">"
  			+ "						<element name=\"none\">"
  			+ "							<field name=\"value\">Full text</field>"
  			+ "						</element>"
  			+ "					</element>"
  			+ "					<element name=\"stage\">"
  			+ "						<element name=\"none\">"
  			+ "							<field name=\"value\">Pre-publication</field>"
  			+ "						</element>"
  			+ "					</element>"
  			+ "				</element>"
  			+ "				<element name=\"anonymity\">"
  			+ "					<element name=\"none\">"
  			+ "						<field name=\"value\">All identities known</field>"
  			+ "					</element>"
  			+ "				</element>"
  			+ "				<element name=\"reviewer\">"
  			+ "					<element name=\"type\">"
  			+ "						<element name=\"none\">"
  			+ "							<field name=\"value\">Internal editor</field>"
  			+ "							<field name=\"value\">External peer reviewer</field>"
  			+ "						</element>"
  			+ "					</element>"
  			+ "				</element>"
  			+ "				<element name=\"open\">"
  			+ "					<element name=\"review\">"
  			+ "						<element name=\"none\">"
  			+ "							<field name=\"value\">No</field>"
  			+ "						</element>"
  			+ "					</element>"
  			+ "				</element>"
  			+ "				<element name=\"publish\">"
  			+ "					<element name=\"responsibility\">"
  			+ "						<element name=\"none\">"
  			+ "							<field name=\"value\">Scientific or Editorial Board</field>"
  			+ "						</element>"
  			+ "					</element>"
  			+ "				</element>"
  			+ "				<element name=\"id\">"
  			+ "					<element name=\"none\">"
  			+ "						<field name=\"value\">8ad5c235-9810-49eb-b358-27c8675324d9</field>"
  			+ "					</element>"
  			+ "				</element>"
  			+ "				<element name=\"title\">"
  			+ "					<element name=\"none\">"
  			+ "						<field name=\"value\">Dissertations (Dissertationen)</field>"
  			+ "					</element>"
  			+ "				</element>"
  			+ "			</element>"
  			+ "			<element name=\"bundles\">"
  			+ "				<element name=\"bundle\">"
  			+ "					<field name=\"name\">THUMBNAIL</field>"
  			+ "					<element name=\"bitstreams\">"
  			+ "						<element name=\"bitstream\">"
  			+ "							<field name=\"name\">807.jpg</field>"
  			+ "							<field name=\"originalName\">807.jpg</field>"
  			+ "							<field name=\"format\">image/jpeg</field>"
  			+ "							<field name=\"size\">157398</field>"
  			+ "							<field name=\"url\">"
  			+ "								https://directory.doabooks.org/bitstream/20.500.12854/45918/1/807.jpg</field>"
  			+ "							<field name=\"checksum\">"
  			+ "								3969bba8f6814782c0c7bf554e80b300</field>"
  			+ "							<field name=\"checksumAlgorithm\">MD5</field>"
  			+ "							<field name=\"sid\">1</field>"
  			+ "							<field name=\"oapenidentifierdownloadUrl\">"
  			+ "								https://www.ksp.kit.edu/9783866447004</field>"
  			+ "							<field name=\"rightsuri\">"
  			+ "								https://creativecommons.org/licenses/by-nc-nd/4.0/</field>"
  			+ "							<field name=\"rights\">CC-BY-NC-ND</field>"
  			+ "						</element>"
  			+ "					</element>"
  			+ "				</element>"
  			+ "				<element name=\"bundle\">"
  			+ "					<field name=\"name\">EXPORT</field>"
  			+ "					<element name=\"bitstreams\">"
  			+ "						<element name=\"bitstream\">"
  			+ "							<field name=\"name\">"
  			+ "								00215d10-785a-48da-8c18-555b8a781d5f.marc.xml</field>"
  			+ "							<field name=\"format\">application/octet-stream</field>"
  			+ "							<field name=\"size\">5202</field>"
  			+ "							<field name=\"url\">"
  			+ "								https://directory.doabooks.org/bitstream/20.500.12854/45918/2/00215d10-785a-48da-8c18-555b8a781d5f.marc.xml</field>"
  			+ "							<field name=\"checksum\">"
  			+ "								ebd8aafb3e5bbc6f25dee26c70f20a66</field>"
  			+ "							<field name=\"checksumAlgorithm\">MD5</field>"
  			+ "							<field name=\"sid\">2</field>"
  			+ "						</element>"
  			+ "						<element name=\"bitstream\">"
  			+ "							<field name=\"name\">"
  			+ "								00215d10-785a-48da-8c18-555b8a781d5f.onix_3.0.xml</field>"
  			+ "							<field name=\"format\">application/octet-stream</field>"
  			+ "							<field name=\"size\">5238</field>"
  			+ "							<field name=\"url\">"
  			+ "								https://directory.doabooks.org/bitstream/20.500.12854/45918/3/00215d10-785a-48da-8c18-555b8a781d5f.onix_3.0.xml</field>"
  			+ "							<field name=\"checksum\">"
  			+ "								e9a444adbc6467753d9eb36bc07a6c77</field>"
  			+ "							<field name=\"checksumAlgorithm\">MD5</field>"
  			+ "							<field name=\"sid\">3</field>"
  			+ "						</element>"
  			+ "						<element name=\"bitstream\">"
  			+ "							<field name=\"name\">"
  			+ "								00215d10-785a-48da-8c18-555b8a781d5f.ris</field>"
  			+ "							<field name=\"format\">application/octet-stream</field>"
  			+ "							<field name=\"size\">862</field>"
  			+ "							<field name=\"url\">"
  			+ "								https://directory.doabooks.org/bitstream/20.500.12854/45918/4/00215d10-785a-48da-8c18-555b8a781d5f.ris</field>"
  			+ "							<field name=\"checksum\">"
  			+ "								9d3bfc304433100fb5f8f8d2d4714444</field>"
  			+ "							<field name=\"checksumAlgorithm\">MD5</field>"
  			+ "							<field name=\"sid\">4</field>"
  			+ "						</element>"
  			+ "						<element name=\"bitstream\">"
  			+ "							<field name=\"name\">"
  			+ "								00215d10-785a-48da-8c18-555b8a781d5f.tsv</field>"
  			+ "							<field name=\"format\">application/octet-stream</field>"
  			+ "							<field name=\"size\">398</field>"
  			+ "							<field name=\"url\">"
  			+ "								https://directory.doabooks.org/bitstream/20.500.12854/45918/-1/00215d10-785a-48da-8c18-555b8a781d5f.tsv</field>"
  			+ "							<field name=\"checksum\">"
  			+ "								83c34ca88b712cda5b09f28cb21e04b1</field>"
  			+ "							<field name=\"checksumAlgorithm\">MD5</field>"
  			+ "							<field name=\"sid\">-1</field>"
  			+ "						</element>"
  			+ "					</element>"
  			+ "				</element>"
  			+ "			</element>"
  			+ "			<element name=\"others\">"
  			+ "				<field name=\"uuid\">00215d10-785a-48da-8c18-555b8a781d5f</field>"
  			+ "				<field name=\"handle\">20.500.12854/45918</field>"
  			+ "				<field name=\"identifier\">"
  			+ "					oai:directory.doabooks.org:20.500.12854/45918</field>"
  			+ "				<field name=\"lastModifyDate\">2024-04-09 23:16:16.838</field>"
  			+ "			</element>"
  			+ "			<element name=\"repository\">"
  			+ "				<field name=\"name\">DOAB PROD Instance</field>"
  			+ "				<field name=\"mail\">info@oapen.org</field>"
  			+ "			</element>"
  			+ "			<element name=\"linkedItemsMetadata\">"
  			+ "				<element name=\"oapen.relation.isPublishedBy\">"
  			+ "					<field name=\"uuid\">68fffc18-8f7b-44fa-ac7e-0b7d7d979bd2</field>"
  			+ "					<field name=\"handle\">20.500.12854/25310</field>"
  			+ "					<element name=\"publisher.name\">"
  			+ "						<field name=\"value\">KIT Scientific Publishing</field>"
  			+ "					</element>"
  			+ "				</element>"
  			+ "			</element>"
  			+ "		</metadata>"
  			+ "	</metadata>"
  			+ "</record>"
  			;
		
	}
